_wandb:
    value:
        cli_version: 0.24.1
        e:
            cs79he44pnc020b01de5gbmcr8null4h:
                args:
                    - --batch_size=64
                    - --cutmix_alpha=0.6060863562658506
                    - --cutout_size=49
                    - --data_dir=C:\Users\ba079778\Downloads\ImageNetSubset\ImageNetSubset
                    - --epochs=30
                    - --label_smoothing=0.051983933147219344
                    - --lr=0.00032626707664144665
                    - --magnitude=14
                    - --mixup_alpha=0.23835815681543557
                    - --model=resnet50
                    - --num_ops=3
                    - --num_workers=8
                    - --optimizer=adamw
                    - --use_cutmix=False
                    - --use_cutout=True
                    - --use_mixup=True
                    - --wandb=True
                    - --wandb_project=resnet-aug
                    - --weight_decay=0.00019528437766849128
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "536863989760"
                        used: "240636383232"
                email: sebastian.drefahl@stud.uni-bamberg.de
                executable: C:\Users\ba079778\.conda\envs\yai\python.exe
                git:
                    commit: ef978600935d4828334a49c4316c08419e321e16
                    remote: https://github.com/deadPixelsGreta/xAI-proj-m-ws2526.git
                gpu: NVIDIA RTX A4000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-4b888224-1652-81da-d561-ffd318011b14
                host: GU130103-05
                memory:
                    total: "68393086976"
                os: Windows-10-10.0.26100-SP0
                program: -m experiments.bagging.scripts.train
                python: CPython 3.11.14
                root: C:\Users\ba079778\Documents\xAI-proj-m-ws2526
                startedAt: "2026-01-30T19:31:58.337361Z"
                writerId: cs79he44pnc020b01de5gbmcr8null4h
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 13
                - 14
                - 16
                - 61
                - 62
            "4": 3.11.14
            "5": 0.24.1
            "8":
                - 3
            "12": 0.24.1
            "13": windows-amd64
architecture:
    value: resnet50
batch_size:
    value: 64
cutmix_alpha:
    value: 0.6060863562658506
cutout_size:
    value: 49
data_dir:
    value: C:\Users\ba079778\Downloads\ImageNetSubset\ImageNetSubset
early_stopping_thresh:
    value: 8
epochs:
    value: 30
freeze_backbone:
    value: false
label_smoothing:
    value: 0.051983933147219344
lr:
    value: 0.00032626707664144665
magnitude:
    value: 14
mixup_alpha:
    value: 0.23835815681543557
model:
    value: resnet50
momentum:
    value: 0.9
num_classes:
    value: 10
num_ops:
    value: 3
num_workers:
    value: 8
optimizer:
    value: adamw
top_n_checkpoints:
    value: 2
use_cutmix:
    value: false
use_cutout:
    value: true
use_mixup:
    value: true
wandb:
    value: true
wandb_project:
    value: resnet-aug
weight_decay:
    value: 0.00019528437766849128
