wandb_version: 1

batch_size:
  value: 32
cutout_size:
  value: 55
data_dir:
  value: C:\Users\ba079778\Downloads\ImageNetSubset\ImageNetSubset
epochs:
  value: 25
lr:
  value: 0.00023661
magnitude:
  value: 7
mixup_alpha:
  value: 0.28044710613093726
model:
  value: resnet50
num_ops:
  value: 3
num_workers:
  value: 8
use_cutout:
  value: false
use_mixup:
  value: true
wandb:
  value: true
wandb_project:
  value: resnet-aug
weight_decay:
  value: 0.0001
