wandb_version: 1

batch_size:
  value: 256
cutout_size:
  value: 55
epochs:
  value: 25
lr:
  value: 0.001423565649056037
magnitude:
  value: 10
mixup_alpha:
  value: 0.2415747765307229
model_name:
  value: resnet50
num_ops:
  value: 4
use_cutout:
  value: true
use_mixup:
  value: true
weight_decay:
  value: 0.0001
