wandb_version: 1

batch_size:
  value: 256
cutout_size:
  value: 41
epochs:
  value: 25
lr:
  value: 0.00255791875293001
magnitude:
  value: 12
mixup_alpha:
  value: 0.16499630339216187
model_name:
  value: resnet50
num_ops:
  value: 4
use_cutout:
  value: true
use_mixup:
  value: false
weight_decay:
  value: 0.0001
