wandb_version: 1

batch_size:
  value: 32
cutout_size:
  value: 25
data_dir:
  value: C:\Users\ba079778\Downloads\ImageNetSubset\ImageNetSubset
epochs:
  value: 25
lr:
  value: 0.0010090984666429393
magnitude:
  value: 10
mixup_alpha:
  value: 0.3705874607960731
model:
  value: resnet50
num_ops:
  value: 2
use_cutout:
  value: false
use_mixup:
  value: true
weight_decay:
  value: 0.0001
