wandb_version: 1

batch_size:
  value: 32
cutmix_alpha:
  value: 1.2289155702335683
cutout_size:
  value: 58
data_dir:
  value: C:\Users\ba079778\Downloads\ImageNetSubset\ImageNetSubset
epochs:
  value: 30
label_smoothing:
  value: 0.21940226332280768
lr:
  value: 0.0001777642411745055
magnitude:
  value: 13
mixup_alpha:
  value: 0.2090092064374735
model:
  value: resnet50
num_ops:
  value: 3
num_workers:
  value: 8
optimizer:
  value: adamw
use_cutmix:
  value: false
use_cutout:
  value: false
use_mixup:
  value: false
wandb:
  value: true
wandb_project:
  value: resnet-aug
weight_decay:
  value: 7.897455101799162e-05
