wandb_version: 1

batch_size:
  value: 32
cutout_size:
  value: 21
epochs:
  value: 25
lr:
  value: 0.001099722054854482
magnitude:
  value: 7
mixup_alpha:
  value: 0.2936659389224211
model:
  value: resnet50
num_ops:
  value: 4
use_cutout:
  value: false
use_mixup:
  value: false
weight_decay:
  value: 0.0001
